# Generated by Django 4.0.3 on 2022-12-11 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
