# Generated by Django 4.0.3 on 2023-05-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Critery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('pora_goda', models.CharField(max_length=200)),
                ('vremya_sutok', models.CharField(max_length=200)),
                ('vid_meropriatia', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Критерий',
                'verbose_name_plural': 'Критерии',
                'ordering': ('name',),
            },
        ),
    ]
