# Generated by Django 4.0.3 on 2023-05-28 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_critery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='critery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.critery'),
            preserve_default=False,
        ),
    ]
