# Generated by Django 4.0.3 on 2022-05-10 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_braintree_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='username',
        ),
    ]
