# Generated by Django 4.0.3 on 2022-05-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_username_order_first_name_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
